spring:

  application:
    name: stock

  kafka:
    consumer:
      group-id: stock-${random.uuid}
      auto-offset-reset: earliest

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"
